SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
	BEGIN TRAN
	SELECT * FROM Accounts WHERE account_id = 1
	
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Accounts WHERE account_id = 1
COMMIT TRAN
-- Problem: UNCOMMITTED/ READ COMMITTED